### ISSUE TITLE
Components R4 and R5 misplaced on the example photo?

### ISSUE THREAD

**Issue by reijndert** [mbarszcz-pcb/c64-rf-modulator-replacement#8]
I assume the schematic is ok, but 
https://github.com/mbarszcz-pcb/c64-rf-modulator-replacement/blob/master/images/photos/c64-rf-modulator-photo-inst.png
the components on position R4 and R5 switched places?
68 ohms and 220 ohms.
Swapping the components doesnt match with  "r4+rv1 approx 68-150" since it starts with 220?

But of course (r4/rv1) and (r5) are a voltage divider and the chroma-out level is still perfectly manageble.

Cheers!

**Comment by mbarszcz-pcb** [comment]
You are correct, they did switch places in Rev C.  The example photo was from Rev B.

`Rev C – 2020-04-05 - Adjusted positioning of several traces, vias, and regulator U1 to improve physical spacing. Changed RV1 and RV2 for "W" footprint trimmers with inline legs due to parts availability. **Swapped R4 and R5 physical locations to better accomodate the new pin configuration**
`
